nome = str(input('Digite seu nome completo aqui: ')).strip()
print('Analisando seu nome ...')
print('Seu nome em maiusculas é {}'.format(nome.upper()))
print('Seu nome em minusculas é {}'.format(nome.lower()))
print('Seu nume sem espaços tem {} letas'.format(len(nome) - nome.count(' ')))
print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))