a = input('Digite algo aqui ...')
print('O tipo primitivo disso é ', type(a))  
print ('É alfabetico?', a.isalpha())
print ('Só tem espaçõs?', a.isspace())
print('É alnumerico?', a.isalnum())
print('Está em maiusculo?', a.isupper())
print('Está em minusculas?', a.islower())
print('Está capitalizada?', a.istitle())